### ISSUE TITLE
Default wrapping column to smallest ruler

### ISSUE THREAD

**Issue by cluther** [stkb/vscode-rewrap#19]
_rewrap.wrappingColumn_ defaults to 0 which seems to produce a wrap somewhere around column 81. It's easy enough to change _rewrap.wrappingColumn_, but I think it would be more intuitive if the default value of 0 would caused the wrapping column to be the smallest value in the _editor.rulers_ configuration array if _editor.rulers_ is set.

My most common use of extension is to wrap Python docstrings to 72 columns where I have my _editor.rulers_ set to `[72, 79]`.

Thanks for the useful extension! I greatly appreciate the effort you've already put into this, and have no expectation that you do anything about this issue. I only opened the issue in case you or anyone else was already thinking about it, and needed a +1.

**Comment by stkb** [comment]
Yeah this seems sensible, and is something I've considered before too. But I kinda have to force myself to stop adding stuff that no one has asked for yet. So feature requests are always welcome!

It's an easy addition too and I'll have it in the next version. It'll work like this (the bold step is new, the rest it does already).
1. If present, use `rewrap.wrappingColumn`
2. **Otherwise if present, use the smallest ruler value**
3. Otherwise, if present and set to something sensible (like <=120), use `editor.wrappingColumn`
4. Otherwise use 80

A note on the default setting: the default is to wrap at column 80 (ie after 80 characters). This shows as col 81 in the vscode editor however.

Thanks also for the kind words and the review. Like most cases I guess, this was something I originally made because I needed the functionality myself, but hearing other people appreciate it makes the effort really worthwhile.

**Comment by cluther** [comment]
Excellent. The steps look good to me. I cant think of any way it could be better, and it'll make my case work with no configuration.

**Comment by stkb** [comment]
Slight change of plan: it'll just use the first value in the list rather than finding the smallest. Makes the code simpler and also gives the user the option to use a ruler other than the smallest if they want.

This will be in the next version (1.0.0) which should be out in the next couple of days.

**Comment by cluther** [comment]
Smart!

**Comment by stkb** [comment]
Ok v1.0.0 is out. Gonna close this now but let me know if anything's not working!
