### ISSUE TITLE
Option to use absolute column width

### ISSUE THREAD

**Issue by calmh** [stkb/vscode-rewrap#2]
Thanks for this plugin! However, I find that I want columns to wrap at (for example) *column* 76, not be 76 characters wide no matter where they start. This means that comments that start at an indent will need to be wrapped narrower to keep below the max column width, but that's fine.

To illustrate with an extreme example, given `rewrap.wrappingColumn: 22` it current does

```
// wrapped at column
// twenty-two.

    // wrapped at column
    // twenty-two.
```

with the second paragraph exceeding column 22, while I would prefer

```
// wrapped at column
// twenty-two.

    // wrapped at
    // column
    // twenty-two.
```

Could there be an option to take the indent into account to accomplish this?

**Comment by stkb** [comment]
Hmm, how you describe (absolute column) is exactly how it should be working, and if it's not, it's a bug.

Are you indenting with tabs or spaces?

**Comment by calmh** [comment]
Tabs. Perhaps the issue, they are seen as one character each?

**Comment by stkb** [comment]
Yeah :) Trying your example with 4-space indents I got the correct result
```
// wrapped at column
// twenty-two.

    // wrapped at
    // column
    // twenty-two.
```
But when using tabs it came out like this, as you described.
```
// wrapped at column
// twenty-two.

    // wrapped at column
    // twenty-two.
```
The issue is indeed that it's counting tabs as one character each for the purpose of working out where to wrap. VSCode doesn't (yet) make the tab display width available to extensions. But hopefully I can detect it in some way.

Genuine general question though, because I've always used spaces: How does fixing everything to a specific column width make sense when using tabs? Because if you for example, render tabs at 2 spaces and then make all your code wrap at column 80, and then someone else reads the code but renders the tabs at 4 spaces each, the line wrapping's all gonna be off. Or does it just not matter?

**Comment by calmh** [comment]
You're right, in that case the wrapping will be off for one of us. I'd say that doesn't matter as it's an inherent property of using tabs for indentation, but that it would be nice if this plugin did the right thing based on the settings it can figure out when it's invoked. :)

**Comment by stkb** [comment]
I've just pushed out a new version that should fix this issue (v0.4.1). Could you let me know if it's now working for you?

**Comment by calmh** [comment]
Looks good :+1:

**Comment by stkb** [comment]
Great. Thanks for reporting!
