### ISSUE TITLE
TOML support

### ISSUE THREAD

**Issue by redactedscribe** [stkb/vscode-rewrap#26]
When using Rewrap in `*.toml` files, wrapping behaves unexpectedly. These same issues do not occur with all file types; `*.toml` is the first I've come across that does this.

Lines beginning with  `+`, `-`, `*` or `@` for example, will ignore any preceding lines and only perform the wrap on the line itself and any that follow contiguously. There may be other symbols with the same behaviour.
```
Lorem ipsum dolor sit amet,
@consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua.
```

A line that specifically begins with a `#` and is followed by white space will not wrap at all.
```
Lorem ipsum dolor sit amet,
# consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua.
```

Thanks.

**Comment by stkb** [comment]
Hi, sorry for the delay in replying to your issues. This reason for this was that any file format unknown to Rewrap gets treated as plaintext, which in turn gets parsed as Markdown format. Therefore lines starting with #, @ etc were getting treated as bullet paragraphs.

That policy was created a while ago in order to accommodate certain types of formatting in plain text, but it's caused some problems lately, so I think I'll just revert to a standard vanilla mode for plain text / unknown files.

Meanwhile I've added a change to master to recognise .toml files, including '#' comment lines. However I wasn't familiar with the TOML language and I'm not sure It'll do everything as you'd like yet, eg preserving the format of multiline strings or being able to format a whole file at once.

I'll leave this issue open for now so you can try it out after the next release (v1.2), which I'll publish in the next day or so, after also working on #25.

**Comment by redactedscribe** [comment]
@stkb: Hey, no problem.

The TOML language isn't one that requires much wrapping due to it mostly storing a list of dependencies and meta data, so I wouldn't be too concerned with supporting it specifically as most lines are short (besides in the rare case that comments are used such as when I tried). It stands to reason that this is down to the unknown/plaintext to Markdown policy that you mentioned. I think treating unknown files only as plaintext will have an overall benefit for unknown files types as at least the behaviour will be uniform.

Thanks.

**Comment by redactedscribe** [comment]
TOML comments now wrap as expected and the rest is treated as plaintext. Thanks.
